function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -1000000; // obj_control
	global.__objectDepths[1] = 0; // obj_control_EBGames
	global.__objectDepths[2] = 0; // obj_control_vista
	global.__objectDepths[3] = 0; // obj_opciones
	global.__objectDepths[4] = 0; // obj_limpieza_mundo
	global.__objectDepths[5] = 0; // obj_control_inmo_pj
	global.__objectDepths[6] = 0; // obj_npcs_mundo
	global.__objectDepths[7] = 0; // obj_items_mundo
	global.__objectDepths[8] = 0; // obj_personas_mundo
	global.__objectDepths[9] = 0; // obj_control_animacion_agua
	global.__objectDepths[10] = -50000; // obj_pausa
	global.__objectDepths[11] = -5; // obj_control_devices
	global.__objectDepths[12] = 0; // obj_control_menu_principal
	global.__objectDepths[13] = 0; // obj_mapas_mundo
	global.__objectDepths[14] = 0; // obj_control_musica
	global.__objectDepths[15] = 0; // obj_sonido_mar
	global.__objectDepths[16] = 0; // obj_control_notificacion_torneos
	global.__objectDepths[17] = 0; // obj_pj
	global.__objectDepths[18] = -500; // obj_arbol_basic
	global.__objectDepths[19] = 0; // obj_arbol_1
	global.__objectDepths[20] = 0; // obj_arbol_2
	global.__objectDepths[21] = 0; // obj_arbol_3
	global.__objectDepths[22] = 0; // obj_arbol_4
	global.__objectDepths[23] = 0; // obj_arbol_5
	global.__objectDepths[24] = 0; // obj_arbol_6
	global.__objectDepths[25] = 0; // obj_arbol_7
	global.__objectDepths[26] = 0; // obj_arbol_8
	global.__objectDepths[27] = 0; // obj_arbol_9
	global.__objectDepths[28] = 0; // obj_arbol_10
	global.__objectDepths[29] = 0; // obj_arbol_11
	global.__objectDepths[30] = 0; // obj_arbol_12
	global.__objectDepths[31] = 0; // obj_arbol_13
	global.__objectDepths[32] = 0; // obj_arbol_14
	global.__objectDepths[33] = 0; // obj_arbol_15
	global.__objectDepths[34] = 0; // obj_arbol_16
	global.__objectDepths[35] = 0; // obj_arbol_17
	global.__objectDepths[36] = 0; // obj_arbol_18
	global.__objectDepths[37] = 0; // obj_arbol_19
	global.__objectDepths[38] = 0; // obj_arbol_20
	global.__objectDepths[39] = 0; // obj_arbol_21
	global.__objectDepths[40] = 0; // obj_cartel_Ringville
	global.__objectDepths[41] = 0; // obj_cartel_Duhmundorth
	global.__objectDepths[42] = 0; // obj_cartel_Greage
	global.__objectDepths[43] = 0; // obj_cartel_Lotch
	global.__objectDepths[44] = 0; // obj_cartel_pociones
	global.__objectDepths[45] = 0; // obj_cartel_carpinteria
	global.__objectDepths[46] = 0; // obj_cartel_armas
	global.__objectDepths[47] = 0; // obj_cartel_sastre
	global.__objectDepths[48] = 0; // obj_cartel_armaduras
	global.__objectDepths[49] = 0; // obj_cartel_mineria
	global.__objectDepths[50] = 0; // obj_cartel_magia
	global.__objectDepths[51] = 0; // obj_cartel_pescadores
	global.__objectDepths[52] = 0; // obj_cartel_finanzas
	global.__objectDepths[53] = 0; // obj_cartel_provisiones
	global.__objectDepths[54] = 0; // obj_cartel_sacerdote
	global.__objectDepths[55] = 0; // obj_cofre_abierto
	global.__objectDepths[56] = 0; // obj_cofre_cerrado
	global.__objectDepths[57] = 0; // obj_lapida
	global.__objectDepths[58] = 0; // obj_barril_1
	global.__objectDepths[59] = 0; // obj_barril_2
	global.__objectDepths[60] = 0; // obj_olla
	global.__objectDepths[61] = 0; // obj_balde
	global.__objectDepths[62] = 0; // obj_cardo
	global.__objectDepths[63] = 0; // obj_casa_p1
	global.__objectDepths[64] = 0; // obj_casa_p2
	global.__objectDepths[65] = -1000; // obj_techo_casa_1
	global.__objectDepths[66] = -1000; // obj_techo_casa_2
	global.__objectDepths[67] = -1000; // obj_techo_casa_3
	global.__objectDepths[68] = -1000; // obj_techo_casa_4
	global.__objectDepths[69] = 0; // obj_mesa_1
	global.__objectDepths[70] = 0; // obj_mesa_2
	global.__objectDepths[71] = 0; // obj_mesa_3
	global.__objectDepths[72] = 0; // obj_mesa_4
	global.__objectDepths[73] = 0; // obj_mesa_5
	global.__objectDepths[74] = 0; // obj_mesa_6
	global.__objectDepths[75] = 0; // obj_biblioteca_1
	global.__objectDepths[76] = 0; // obj_biblioteca_2
	global.__objectDepths[77] = 0; // obj_biblioteca_3
	global.__objectDepths[78] = 0; // obj_armas
	global.__objectDepths[79] = 0; // obj_canias
	global.__objectDepths[80] = 0; // obj_repisa_copas
	global.__objectDepths[81] = 0; // obj_repisa_ollas
	global.__objectDepths[82] = 0; // obj_colgante_pez_1
	global.__objectDepths[83] = 0; // obj_colgante_pez_2
	global.__objectDepths[84] = 0; // obj_puerta_1
	global.__objectDepths[85] = 0; // obj_puerta_2
	global.__objectDepths[86] = 0; // obj_puerta_3
	global.__objectDepths[87] = 0; // obj_puerta_4
	global.__objectDepths[88] = 0; // obj_puerta_5
	global.__objectDepths[89] = 0; // obj_puerta_6
	global.__objectDepths[90] = 0; // obj_puerta_7
	global.__objectDepths[91] = 0; // obj_columna
	global.__objectDepths[92] = 0; // obj_pared_hor
	global.__objectDepths[93] = 0; // obj_pared_ver
	global.__objectDepths[94] = 0; // obj_valla_hor
	global.__objectDepths[95] = 0; // obj_valla_ver
	global.__objectDepths[96] = 0; // obj_reja_hor
	global.__objectDepths[97] = 0; // obj_reja_ver_der
	global.__objectDepths[98] = 0; // obj_reja_ver_izq
	global.__objectDepths[99] = 0; // obj_hogar
	global.__objectDepths[100] = 0; // obj_hogar_sin_chimenea
	global.__objectDepths[101] = 0; // obj_vela
	global.__objectDepths[102] = 0; // obj_farol
	global.__objectDepths[103] = 0; // obj_cruz
	global.__objectDepths[104] = 0; // obj_cactus
	global.__objectDepths[105] = 0; // obj_planta
	global.__objectDepths[106] = 0; // obj_pico_nevado_izq
	global.__objectDepths[107] = 0; // obj_pico_nevado_der
	global.__objectDepths[108] = -1000; // obj_arco_catacumbas_hor
	global.__objectDepths[109] = -1000; // obj_arco_catacumbas_ver
	global.__objectDepths[110] = 0; // obj_organo
	global.__objectDepths[111] = 0; // obj_banco_iglesia
	global.__objectDepths[112] = 0; // obj_baranda
	global.__objectDepths[113] = 0; // obj_altar
	global.__objectDepths[114] = 0; // obj_fuente
	global.__objectDepths[115] = 0; // obj_entrada_DNW
	global.__objectDepths[116] = 0; // obj_entrada_DSOP
	global.__objectDepths[117] = 0; // obj_entrada_minas
	global.__objectDepths[118] = 0; // obj_pared_ver_larga_Greage
	global.__objectDepths[119] = 0; // obj_pared_ver_media_1_Greage
	global.__objectDepths[120] = 0; // obj_pared_ver_media_2_Greage
	global.__objectDepths[121] = 0; // obj_pared_ver_corta_Greage
	global.__objectDepths[122] = -1000; // obj_techo_1_Greage
	global.__objectDepths[123] = -1000; // obj_techo_2_Greage
	global.__objectDepths[124] = -1000; // obj_techo_1_Lotch
	global.__objectDepths[125] = -1000; // obj_techo_2_Lotch
	global.__objectDepths[126] = -1000; // obj_techo_3_Lotch
	global.__objectDepths[127] = -1000; // obj_techo_4_Lotch
	global.__objectDepths[128] = -1000; // obj_techo_1_Ringville
	global.__objectDepths[129] = -1000; // obj_techo_2_Ringville
	global.__objectDepths[130] = -1000; // obj_techo_1_Duhmundorth
	global.__objectDepths[131] = -1000; // obj_techo_2_Duhmundorth
	global.__objectDepths[132] = -1000; // obj_techo_3_Duhmundorth
	global.__objectDepths[133] = -1000; // obj_techo_4_Duhmundorth
	global.__objectDepths[134] = -1000; // obj_techo_5_Duhmundorth
	global.__objectDepths[135] = 0; // obj_bloque_basic
	global.__objectDepths[136] = 0; // obj_bloque
	global.__objectDepths[137] = 0; // obj_bloqueo_agua
	global.__objectDepths[138] = 0; // obj_bloqueo_tierra
	global.__objectDepths[139] = 0; // obj_bloqueo_arboles
	global.__objectDepths[140] = 0; // obj_telep
	global.__objectDepths[141] = 0; // obj_tp
	global.__objectDepths[142] = 0; // obj_bloqueo_minas
	global.__objectDepths[143] = 0; // obj_bloqueo
	global.__objectDepths[144] = 0; // obj_juncos_agua
	global.__objectDepths[145] = 0; // obj_hojas_agua
	global.__objectDepths[146] = 0; // obj_minas
	global.__objectDepths[147] = 0; // obj_fragua
	global.__objectDepths[148] = 0; // obj_tile_invalido
	global.__objectDepths[149] = 0; // obj_npc_basic
	global.__objectDepths[150] = 0; // obj_npc_murcielago
	global.__objectDepths[151] = 0; // obj_npc_serpiente
	global.__objectDepths[152] = 0; // obj_npc_esqueleto
	global.__objectDepths[153] = 0; // obj_npc_bandido
	global.__objectDepths[154] = 0; // obj_npc_esqueleto_guerrero
	global.__objectDepths[155] = 0; // obj_npc_zombie
	global.__objectDepths[156] = 0; // obj_npc_lord_zombie
	global.__objectDepths[157] = 0; // obj_npc_goblin
	global.__objectDepths[158] = 0; // obj_npc_duende
	global.__objectDepths[159] = 0; // obj_npc_orco
	global.__objectDepths[160] = 0; // obj_npc_hormiga_gigante
	global.__objectDepths[161] = 0; // obj_npc_asesino
	global.__objectDepths[162] = 0; // obj_npc_ogro
	global.__objectDepths[163] = 0; // obj_npc_beholder
	global.__objectDepths[164] = 0; // obj_npc_liche
	global.__objectDepths[165] = 0; // obj_npc_lord_orco
	global.__objectDepths[166] = 0; // obj_npc_dragon_pequenio
	global.__objectDepths[167] = 0; // obj_npc_golem
	global.__objectDepths[168] = 0; // obj_npc_hormiga
	global.__objectDepths[169] = 0; // obj_npc_rata
	global.__objectDepths[170] = 0; // obj_npc_cuervo
	global.__objectDepths[171] = 0; // obj_npc_aguila
	global.__objectDepths[172] = 0; // obj_npc_gallo
	global.__objectDepths[173] = 0; // obj_npc_lobo
	global.__objectDepths[174] = 0; // obj_npc_tortuga
	global.__objectDepths[175] = 0; // obj_npc_jabali
	global.__objectDepths[176] = 0; // obj_npc_oso_pardo
	global.__objectDepths[177] = 0; // obj_npc_tigre
	global.__objectDepths[178] = 0; // obj_npc_escorpion
	global.__objectDepths[179] = 0; // obj_npc_arania
	global.__objectDepths[180] = 0; // obj_npc_viuda_negra
	global.__objectDepths[181] = 0; // obj_npc_duende_molesto
	global.__objectDepths[182] = 0; // obj_npc_orco_brujo
	global.__objectDepths[183] = 0; // obj_npc_mago_malvado
	global.__objectDepths[184] = 0; // obj_npc_bruja
	global.__objectDepths[185] = 0; // obj_npc_medusa
	global.__objectDepths[186] = 0; // obj_npc_dragonic
	global.__objectDepths[187] = 0; // obj_npc_lobo_invernal
	global.__objectDepths[188] = 0; // obj_npc_oso_polar
	global.__objectDepths[189] = 0; // obj_npc_yeti
	global.__objectDepths[190] = 0; // obj_npc_golem_hielo
	global.__objectDepths[191] = 0; // obj_npc_calamar
	global.__objectDepths[192] = 0; // obj_npc_galeon_fantasmal
	global.__objectDepths[193] = 0; // obj_npc_leviatan
	global.__objectDepths[194] = 0; // obj_npc_lobo_invocado
	global.__objectDepths[195] = 0; // obj_npc_zombie_invocado
	global.__objectDepths[196] = 0; // obj_npc_ele_agua_invocado
	global.__objectDepths[197] = 0; // obj_npc_ele_tierra_invocado
	global.__objectDepths[198] = 0; // obj_npc_ele_fuego_invocado
	global.__objectDepths[199] = 0; // obj_npc_cura
	global.__objectDepths[200] = 0; // obj_npc_carpintero
	global.__objectDepths[201] = 0; // obj_npc_armas
	global.__objectDepths[202] = 0; // obj_npc_armaduras
	global.__objectDepths[203] = 0; // obj_npc_cascos_escudos
	global.__objectDepths[204] = 0; // obj_npc_sastre
	global.__objectDepths[205] = 0; // obj_npc_sastre_tunicas
	global.__objectDepths[206] = 0; // obj_npc_sastre_bajos
	global.__objectDepths[207] = 0; // obj_npc_mago
	global.__objectDepths[208] = 0; // obj_npc_hechizos
	global.__objectDepths[209] = 0; // obj_npc_pescador
	global.__objectDepths[210] = 0; // obj_npc_comidas
	global.__objectDepths[211] = 0; // obj_npc_bebidas
	global.__objectDepths[212] = 0; // obj_npc_pociones
	global.__objectDepths[213] = 0; // obj_npc_herrero
	global.__objectDepths[214] = 0; // obj_npc_banquero
	global.__objectDepths[215] = 0; // obj_rey
	global.__objectDepths[216] = 0; // obj_Lord_Thek
	global.__objectDepths[217] = 0; // obj_banco
	global.__objectDepths[218] = 0; // obj_respawn_personas
	global.__objectDepths[219] = 0; // obj_persona
	global.__objectDepths[220] = -1000; // obj_techo_basic
	global.__objectDepths[221] = -1000; // obj_techo_basico
	global.__objectDepths[222] = -1000; // obj_techo_arriba
	global.__objectDepths[223] = -1000; // obj_techo_abajo
	global.__objectDepths[224] = -1000; // obj_techo_izq
	global.__objectDepths[225] = -1000; // obj_techo_der
	global.__objectDepths[226] = -1000; // obj_techo_izq_arriba
	global.__objectDepths[227] = -1000; // obj_techo_der_arriba
	global.__objectDepths[228] = -1000; // obj_techo_izq_abajo
	global.__objectDepths[229] = -1000; // obj_techo_der_abajo
	global.__objectDepths[230] = -1000; // obj_techo_esq_izq_arriba
	global.__objectDepths[231] = -1000; // obj_techo_esq_der_arriba
	global.__objectDepths[232] = -1000; // obj_techo_esq_izq_abajo
	global.__objectDepths[233] = -1000; // obj_techo_esq_der_abajo
	global.__objectDepths[234] = -1; // obj_arma
	global.__objectDepths[235] = 0; // obj_escudo
	global.__objectDepths[236] = 0; // obj_arma_persona
	global.__objectDepths[237] = 0; // obj_escudo_persona
	global.__objectDepths[238] = 0; // obj_menu_crearPJ
	global.__objectDepths[239] = 0; // obj_menu_seleccionarPJ
	global.__objectDepths[240] = 0; // obj_menu_opciones
	global.__objectDepths[241] = 0; // obj_menu_creditos
	global.__objectDepths[242] = 0; // obj_menu_salir
	global.__objectDepths[243] = 0; // obj_boton_crearPJ_basic
	global.__objectDepths[244] = 0; // obj_flecha_skills_izq
	global.__objectDepths[245] = 0; // obj_flecha_skills_der
	global.__objectDepths[246] = 0; // obj_skills
	global.__objectDepths[247] = 0; // obj_flecha_clase_izq
	global.__objectDepths[248] = 0; // obj_flecha_clase_der
	global.__objectDepths[249] = 0; // obj_flecha_raza_izq
	global.__objectDepths[250] = 0; // obj_flecha_raza_der
	global.__objectDepths[251] = 0; // obj_flecha_sexo_izq
	global.__objectDepths[252] = 0; // obj_flecha_sexo_der
	global.__objectDepths[253] = 0; // obj_nombrePJ
	global.__objectDepths[254] = 0; // obj_dados
	global.__objectDepths[255] = 0; // obj_crearPJ
	global.__objectDepths[256] = 0; // obj_volverAMenu
	global.__objectDepths[257] = 0; // obj_room_nombre
	global.__objectDepths[258] = 0; // obj_boton_panel_skills_izq
	global.__objectDepths[259] = 0; // obj_boton_panel_skills_der
	global.__objectDepths[260] = 0; // obj_seleccionarPJ_1
	global.__objectDepths[261] = 0; // obj_seleccionarPJ_2
	global.__objectDepths[262] = 0; // obj_seleccionarPJ_3
	global.__objectDepths[263] = 0; // obj_seleccionarPJ_4
	global.__objectDepths[264] = 0; // obj_seleccionarPJ_5
	global.__objectDepths[265] = 0; // obj_seleccionarPJ_6
	global.__objectDepths[266] = 0; // obj_seleccionarPJ_7
	global.__objectDepths[267] = 0; // obj_seleccionarPJ_8
	global.__objectDepths[268] = 0; // obj_seleccionarPJ_9
	global.__objectDepths[269] = 0; // obj_seleccionarPJ_volver
	global.__objectDepths[270] = 0; // obj_seleccionarPJ_elegir
	global.__objectDepths[271] = 0; // obj_seleccionarPJ_borrar
	global.__objectDepths[272] = 0; // obj_control_seleccionarPJ
	global.__objectDepths[273] = 0; // obj_opciones_dif_media
	global.__objectDepths[274] = 0; // obj_opciones_dif_alta
	global.__objectDepths[275] = 0; // obj_opciones_sim_horarios
	global.__objectDepths[276] = 0; // obj_opciones_no_sim_horarios
	global.__objectDepths[277] = 0; // obj_opciones_volver
	global.__objectDepths[278] = 0; // obj_control_opciones
	global.__objectDepths[279] = 0; // obj_control_creditos
	global.__objectDepths[280] = -75000; // obj_manual
	global.__objectDepths[281] = -75001; // obj_flecha_der_manual
	global.__objectDepths[282] = -75001; // obj_flecha_izq_manual
	global.__objectDepths[283] = -75001; // obj_indice_manual
	global.__objectDepths[284] = -75001; // obj_indice_manual_1
	global.__objectDepths[285] = -75001; // obj_indice_manual_2
	global.__objectDepths[286] = -75001; // obj_indice_manual_3
	global.__objectDepths[287] = -75001; // obj_indice_manual_4
	global.__objectDepths[288] = -75001; // obj_indice_manual_5
	global.__objectDepths[289] = -75001; // obj_indice_manual_6
	global.__objectDepths[290] = -75001; // obj_indice_manual_7
	global.__objectDepths[291] = -75001; // obj_indice_manual_8
	global.__objectDepths[292] = -75001; // obj_indice_manual_9
	global.__objectDepths[293] = -75001; // obj_indice_manual_10
	global.__objectDepths[294] = -75001; // obj_indice_manual_11
	global.__objectDepths[295] = -75001; // obj_indice_manual_12
	global.__objectDepths[296] = -50000; // obj_gui
	global.__objectDepths[297] = 0; // obj_flecha_abajo
	global.__objectDepths[298] = 0; // obj_flecha_arriba
	global.__objectDepths[299] = 0; // obj_flecha_izq
	global.__objectDepths[300] = 0; // obj_flecha_der
	global.__objectDepths[301] = 0; // obj_tecla_ctrl
	global.__objectDepths[302] = 0; // obj_tecla_A
	global.__objectDepths[303] = 0; // obj_tecla_U
	global.__objectDepths[304] = 0; // obj_tecla_lanzar
	global.__objectDepths[305] = 0; // obj_tecla_hechizos
	global.__objectDepths[306] = 0; // obj_tecla_inventario
	global.__objectDepths[307] = 0; // obj_tecla_T
	global.__objectDepths[308] = 0; // obj_tecla_f6
	global.__objectDepths[309] = -50000; // obj_msg
	global.__objectDepths[310] = 0; // obj_skills_libres
	global.__objectDepths[311] = 0; // obj_seguro
	global.__objectDepths[312] = 0; // obj_ayuda
	global.__objectDepths[313] = 0; // obj_configuracion
	global.__objectDepths[314] = 0; // obj_panel_opciones
	global.__objectDepths[315] = 0; // obj_panel_items
	global.__objectDepths[316] = 0; // obj_panel_trabajos
	global.__objectDepths[317] = 0; // obj_area_flechas
	global.__objectDepths[318] = 0; // obj_boton_pausa
	global.__objectDepths[319] = -75000; // obj_borde_mapa
	global.__objectDepths[320] = 0; // obj_opcion_sonido
	global.__objectDepths[321] = -50000; // obj_numpad
	global.__objectDepths[322] = 0; // obj_msj_basic
	global.__objectDepths[323] = -50000; // obj_INFO
	global.__objectDepths[324] = -50000; // obj_efecto_dano
	global.__objectDepths[325] = -50000; // obj_efecto_subir_skill
	global.__objectDepths[326] = -50000; // obj_efecto_falta_skill
	global.__objectDepths[327] = 0; // obj_efecto_subir_lvl
	global.__objectDepths[328] = 0; // obj_efecto_login
	global.__objectDepths[329] = 0; // obj_vibracion
	global.__objectDepths[330] = 0; // obj_particula
	global.__objectDepths[331] = 0; // obj_nubes
	global.__objectDepths[332] = 100000000; // obj_pez
	global.__objectDepths[333] = 0; // obj_inventario
	global.__objectDepths[334] = 0; // obj_hechizos
	global.__objectDepths[335] = 0; // obj_cambiar_vista_hechizos
	global.__objectDepths[336] = 0; // obj_item_basic
	global.__objectDepths[337] = 10000; // obj_oro
	global.__objectDepths[338] = 10000; // obj_item
	global.__objectDepths[339] = 0; // obj_meditacion
	global.__objectDepths[340] = 0; // obj_curar_veneno
	global.__objectDepths[341] = 0; // obj_curar_heridas_leves
	global.__objectDepths[342] = 0; // obj_curar_heridas_graves
	global.__objectDepths[343] = 0; // obj_dardo_magico
	global.__objectDepths[344] = 0; // obj_flecha_magica
	global.__objectDepths[345] = 0; // obj_flecha_electrica
	global.__objectDepths[346] = 0; // obj_misil_magico
	global.__objectDepths[347] = 0; // obj_tormenta_de_fuego
	global.__objectDepths[348] = 0; // obj_descarga_electrica
	global.__objectDepths[349] = 0; // obj_apocalipsis
	global.__objectDepths[350] = 0; // obj_paralizar
	global.__objectDepths[351] = 0; // obj_inmovilizar


	global.__objectNames[0] = "obj_control";
	global.__objectNames[1] = "obj_control_EBGames";
	global.__objectNames[2] = "obj_control_vista";
	global.__objectNames[3] = "obj_opciones";
	global.__objectNames[4] = "obj_limpieza_mundo";
	global.__objectNames[5] = "obj_control_inmo_pj";
	global.__objectNames[6] = "obj_npcs_mundo";
	global.__objectNames[7] = "obj_items_mundo";
	global.__objectNames[8] = "obj_personas_mundo";
	global.__objectNames[9] = "obj_control_animacion_agua";
	global.__objectNames[10] = "obj_pausa";
	global.__objectNames[11] = "obj_control_devices";
	global.__objectNames[12] = "obj_control_menu_principal";
	global.__objectNames[13] = "obj_mapas_mundo";
	global.__objectNames[14] = "obj_control_musica";
	global.__objectNames[15] = "obj_sonido_mar";
	global.__objectNames[16] = "obj_control_notificacion_torneos";
	global.__objectNames[17] = "obj_pj";
	global.__objectNames[18] = "obj_arbol_basic";
	global.__objectNames[19] = "obj_arbol_1";
	global.__objectNames[20] = "obj_arbol_2";
	global.__objectNames[21] = "obj_arbol_3";
	global.__objectNames[22] = "obj_arbol_4";
	global.__objectNames[23] = "obj_arbol_5";
	global.__objectNames[24] = "obj_arbol_6";
	global.__objectNames[25] = "obj_arbol_7";
	global.__objectNames[26] = "obj_arbol_8";
	global.__objectNames[27] = "obj_arbol_9";
	global.__objectNames[28] = "obj_arbol_10";
	global.__objectNames[29] = "obj_arbol_11";
	global.__objectNames[30] = "obj_arbol_12";
	global.__objectNames[31] = "obj_arbol_13";
	global.__objectNames[32] = "obj_arbol_14";
	global.__objectNames[33] = "obj_arbol_15";
	global.__objectNames[34] = "obj_arbol_16";
	global.__objectNames[35] = "obj_arbol_17";
	global.__objectNames[36] = "obj_arbol_18";
	global.__objectNames[37] = "obj_arbol_19";
	global.__objectNames[38] = "obj_arbol_20";
	global.__objectNames[39] = "obj_arbol_21";
	global.__objectNames[40] = "obj_cartel_Ringville";
	global.__objectNames[41] = "obj_cartel_Duhmundorth";
	global.__objectNames[42] = "obj_cartel_Greage";
	global.__objectNames[43] = "obj_cartel_Lotch";
	global.__objectNames[44] = "obj_cartel_pociones";
	global.__objectNames[45] = "obj_cartel_carpinteria";
	global.__objectNames[46] = "obj_cartel_armas";
	global.__objectNames[47] = "obj_cartel_sastre";
	global.__objectNames[48] = "obj_cartel_armaduras";
	global.__objectNames[49] = "obj_cartel_mineria";
	global.__objectNames[50] = "obj_cartel_magia";
	global.__objectNames[51] = "obj_cartel_pescadores";
	global.__objectNames[52] = "obj_cartel_finanzas";
	global.__objectNames[53] = "obj_cartel_provisiones";
	global.__objectNames[54] = "obj_cartel_sacerdote";
	global.__objectNames[55] = "obj_cofre_abierto";
	global.__objectNames[56] = "obj_cofre_cerrado";
	global.__objectNames[57] = "obj_lapida";
	global.__objectNames[58] = "obj_barril_1";
	global.__objectNames[59] = "obj_barril_2";
	global.__objectNames[60] = "obj_olla";
	global.__objectNames[61] = "obj_balde";
	global.__objectNames[62] = "obj_cardo";
	global.__objectNames[63] = "obj_casa_p1";
	global.__objectNames[64] = "obj_casa_p2";
	global.__objectNames[65] = "obj_techo_casa_1";
	global.__objectNames[66] = "obj_techo_casa_2";
	global.__objectNames[67] = "obj_techo_casa_3";
	global.__objectNames[68] = "obj_techo_casa_4";
	global.__objectNames[69] = "obj_mesa_1";
	global.__objectNames[70] = "obj_mesa_2";
	global.__objectNames[71] = "obj_mesa_3";
	global.__objectNames[72] = "obj_mesa_4";
	global.__objectNames[73] = "obj_mesa_5";
	global.__objectNames[74] = "obj_mesa_6";
	global.__objectNames[75] = "obj_biblioteca_1";
	global.__objectNames[76] = "obj_biblioteca_2";
	global.__objectNames[77] = "obj_biblioteca_3";
	global.__objectNames[78] = "obj_armas";
	global.__objectNames[79] = "obj_canias";
	global.__objectNames[80] = "obj_repisa_copas";
	global.__objectNames[81] = "obj_repisa_ollas";
	global.__objectNames[82] = "obj_colgante_pez_1";
	global.__objectNames[83] = "obj_colgante_pez_2";
	global.__objectNames[84] = "obj_puerta_1";
	global.__objectNames[85] = "obj_puerta_2";
	global.__objectNames[86] = "obj_puerta_3";
	global.__objectNames[87] = "obj_puerta_4";
	global.__objectNames[88] = "obj_puerta_5";
	global.__objectNames[89] = "obj_puerta_6";
	global.__objectNames[90] = "obj_puerta_7";
	global.__objectNames[91] = "obj_columna";
	global.__objectNames[92] = "obj_pared_hor";
	global.__objectNames[93] = "obj_pared_ver";
	global.__objectNames[94] = "obj_valla_hor";
	global.__objectNames[95] = "obj_valla_ver";
	global.__objectNames[96] = "obj_reja_hor";
	global.__objectNames[97] = "obj_reja_ver_der";
	global.__objectNames[98] = "obj_reja_ver_izq";
	global.__objectNames[99] = "obj_hogar";
	global.__objectNames[100] = "obj_hogar_sin_chimenea";
	global.__objectNames[101] = "obj_vela";
	global.__objectNames[102] = "obj_farol";
	global.__objectNames[103] = "obj_cruz";
	global.__objectNames[104] = "obj_cactus";
	global.__objectNames[105] = "obj_planta";
	global.__objectNames[106] = "obj_pico_nevado_izq";
	global.__objectNames[107] = "obj_pico_nevado_der";
	global.__objectNames[108] = "obj_arco_catacumbas_hor";
	global.__objectNames[109] = "obj_arco_catacumbas_ver";
	global.__objectNames[110] = "obj_organo";
	global.__objectNames[111] = "obj_banco_iglesia";
	global.__objectNames[112] = "obj_baranda";
	global.__objectNames[113] = "obj_altar";
	global.__objectNames[114] = "obj_fuente";
	global.__objectNames[115] = "obj_entrada_DNW";
	global.__objectNames[116] = "obj_entrada_DSOP";
	global.__objectNames[117] = "obj_entrada_minas";
	global.__objectNames[118] = "obj_pared_ver_larga_Greage";
	global.__objectNames[119] = "obj_pared_ver_media_1_Greage";
	global.__objectNames[120] = "obj_pared_ver_media_2_Greage";
	global.__objectNames[121] = "obj_pared_ver_corta_Greage";
	global.__objectNames[122] = "obj_techo_1_Greage";
	global.__objectNames[123] = "obj_techo_2_Greage";
	global.__objectNames[124] = "obj_techo_1_Lotch";
	global.__objectNames[125] = "obj_techo_2_Lotch";
	global.__objectNames[126] = "obj_techo_3_Lotch";
	global.__objectNames[127] = "obj_techo_4_Lotch";
	global.__objectNames[128] = "obj_techo_1_Ringville";
	global.__objectNames[129] = "obj_techo_2_Ringville";
	global.__objectNames[130] = "obj_techo_1_Duhmundorth";
	global.__objectNames[131] = "obj_techo_2_Duhmundorth";
	global.__objectNames[132] = "obj_techo_3_Duhmundorth";
	global.__objectNames[133] = "obj_techo_4_Duhmundorth";
	global.__objectNames[134] = "obj_techo_5_Duhmundorth";
	global.__objectNames[135] = "obj_bloque_basic";
	global.__objectNames[136] = "obj_bloque";
	global.__objectNames[137] = "obj_bloqueo_agua";
	global.__objectNames[138] = "obj_bloqueo_tierra";
	global.__objectNames[139] = "obj_bloqueo_arboles";
	global.__objectNames[140] = "obj_telep";
	global.__objectNames[141] = "obj_tp";
	global.__objectNames[142] = "obj_bloqueo_minas";
	global.__objectNames[143] = "obj_bloqueo";
	global.__objectNames[144] = "obj_juncos_agua";
	global.__objectNames[145] = "obj_hojas_agua";
	global.__objectNames[146] = "obj_minas";
	global.__objectNames[147] = "obj_fragua";
	global.__objectNames[148] = "obj_tile_invalido";
	global.__objectNames[149] = "obj_npc_basic";
	global.__objectNames[150] = "obj_npc_murcielago";
	global.__objectNames[151] = "obj_npc_serpiente";
	global.__objectNames[152] = "obj_npc_esqueleto";
	global.__objectNames[153] = "obj_npc_bandido";
	global.__objectNames[154] = "obj_npc_esqueleto_guerrero";
	global.__objectNames[155] = "obj_npc_zombie";
	global.__objectNames[156] = "obj_npc_lord_zombie";
	global.__objectNames[157] = "obj_npc_goblin";
	global.__objectNames[158] = "obj_npc_duende";
	global.__objectNames[159] = "obj_npc_orco";
	global.__objectNames[160] = "obj_npc_hormiga_gigante";
	global.__objectNames[161] = "obj_npc_asesino";
	global.__objectNames[162] = "obj_npc_ogro";
	global.__objectNames[163] = "obj_npc_beholder";
	global.__objectNames[164] = "obj_npc_liche";
	global.__objectNames[165] = "obj_npc_lord_orco";
	global.__objectNames[166] = "obj_npc_dragon_pequenio";
	global.__objectNames[167] = "obj_npc_golem";
	global.__objectNames[168] = "obj_npc_hormiga";
	global.__objectNames[169] = "obj_npc_rata";
	global.__objectNames[170] = "obj_npc_cuervo";
	global.__objectNames[171] = "obj_npc_aguila";
	global.__objectNames[172] = "obj_npc_gallo";
	global.__objectNames[173] = "obj_npc_lobo";
	global.__objectNames[174] = "obj_npc_tortuga";
	global.__objectNames[175] = "obj_npc_jabali";
	global.__objectNames[176] = "obj_npc_oso_pardo";
	global.__objectNames[177] = "obj_npc_tigre";
	global.__objectNames[178] = "obj_npc_escorpion";
	global.__objectNames[179] = "obj_npc_arania";
	global.__objectNames[180] = "obj_npc_viuda_negra";
	global.__objectNames[181] = "obj_npc_duende_molesto";
	global.__objectNames[182] = "obj_npc_orco_brujo";
	global.__objectNames[183] = "obj_npc_mago_malvado";
	global.__objectNames[184] = "obj_npc_bruja";
	global.__objectNames[185] = "obj_npc_medusa";
	global.__objectNames[186] = "obj_npc_dragonic";
	global.__objectNames[187] = "obj_npc_lobo_invernal";
	global.__objectNames[188] = "obj_npc_oso_polar";
	global.__objectNames[189] = "obj_npc_yeti";
	global.__objectNames[190] = "obj_npc_golem_hielo";
	global.__objectNames[191] = "obj_npc_calamar";
	global.__objectNames[192] = "obj_npc_galeon_fantasmal";
	global.__objectNames[193] = "obj_npc_leviatan";
	global.__objectNames[194] = "obj_npc_lobo_invocado";
	global.__objectNames[195] = "obj_npc_zombie_invocado";
	global.__objectNames[196] = "obj_npc_ele_agua_invocado";
	global.__objectNames[197] = "obj_npc_ele_tierra_invocado";
	global.__objectNames[198] = "obj_npc_ele_fuego_invocado";
	global.__objectNames[199] = "obj_npc_cura";
	global.__objectNames[200] = "obj_npc_carpintero";
	global.__objectNames[201] = "obj_npc_armas";
	global.__objectNames[202] = "obj_npc_armaduras";
	global.__objectNames[203] = "obj_npc_cascos_escudos";
	global.__objectNames[204] = "obj_npc_sastre";
	global.__objectNames[205] = "obj_npc_sastre_tunicas";
	global.__objectNames[206] = "obj_npc_sastre_bajos";
	global.__objectNames[207] = "obj_npc_mago";
	global.__objectNames[208] = "obj_npc_hechizos";
	global.__objectNames[209] = "obj_npc_pescador";
	global.__objectNames[210] = "obj_npc_comidas";
	global.__objectNames[211] = "obj_npc_bebidas";
	global.__objectNames[212] = "obj_npc_pociones";
	global.__objectNames[213] = "obj_npc_herrero";
	global.__objectNames[214] = "obj_npc_banquero";
	global.__objectNames[215] = "obj_rey";
	global.__objectNames[216] = "obj_Lord_Thek";
	global.__objectNames[217] = "obj_banco";
	global.__objectNames[218] = "obj_respawn_personas";
	global.__objectNames[219] = "obj_persona";
	global.__objectNames[220] = "obj_techo_basic";
	global.__objectNames[221] = "obj_techo_basico";
	global.__objectNames[222] = "obj_techo_arriba";
	global.__objectNames[223] = "obj_techo_abajo";
	global.__objectNames[224] = "obj_techo_izq";
	global.__objectNames[225] = "obj_techo_der";
	global.__objectNames[226] = "obj_techo_izq_arriba";
	global.__objectNames[227] = "obj_techo_der_arriba";
	global.__objectNames[228] = "obj_techo_izq_abajo";
	global.__objectNames[229] = "obj_techo_der_abajo";
	global.__objectNames[230] = "obj_techo_esq_izq_arriba";
	global.__objectNames[231] = "obj_techo_esq_der_arriba";
	global.__objectNames[232] = "obj_techo_esq_izq_abajo";
	global.__objectNames[233] = "obj_techo_esq_der_abajo";
	global.__objectNames[234] = "obj_arma";
	global.__objectNames[235] = "obj_escudo";
	global.__objectNames[236] = "obj_arma_persona";
	global.__objectNames[237] = "obj_escudo_persona";
	global.__objectNames[238] = "obj_menu_crearPJ";
	global.__objectNames[239] = "obj_menu_seleccionarPJ";
	global.__objectNames[240] = "obj_menu_opciones";
	global.__objectNames[241] = "obj_menu_creditos";
	global.__objectNames[242] = "obj_menu_salir";
	global.__objectNames[243] = "obj_boton_crearPJ_basic";
	global.__objectNames[244] = "obj_flecha_skills_izq";
	global.__objectNames[245] = "obj_flecha_skills_der";
	global.__objectNames[246] = "obj_skills";
	global.__objectNames[247] = "obj_flecha_clase_izq";
	global.__objectNames[248] = "obj_flecha_clase_der";
	global.__objectNames[249] = "obj_flecha_raza_izq";
	global.__objectNames[250] = "obj_flecha_raza_der";
	global.__objectNames[251] = "obj_flecha_sexo_izq";
	global.__objectNames[252] = "obj_flecha_sexo_der";
	global.__objectNames[253] = "obj_nombrePJ";
	global.__objectNames[254] = "obj_dados";
	global.__objectNames[255] = "obj_crearPJ";
	global.__objectNames[256] = "obj_volverAMenu";
	global.__objectNames[257] = "obj_room_nombre";
	global.__objectNames[258] = "obj_boton_panel_skills_izq";
	global.__objectNames[259] = "obj_boton_panel_skills_der";
	global.__objectNames[260] = "obj_seleccionarPJ_1";
	global.__objectNames[261] = "obj_seleccionarPJ_2";
	global.__objectNames[262] = "obj_seleccionarPJ_3";
	global.__objectNames[263] = "obj_seleccionarPJ_4";
	global.__objectNames[264] = "obj_seleccionarPJ_5";
	global.__objectNames[265] = "obj_seleccionarPJ_6";
	global.__objectNames[266] = "obj_seleccionarPJ_7";
	global.__objectNames[267] = "obj_seleccionarPJ_8";
	global.__objectNames[268] = "obj_seleccionarPJ_9";
	global.__objectNames[269] = "obj_seleccionarPJ_volver";
	global.__objectNames[270] = "obj_seleccionarPJ_elegir";
	global.__objectNames[271] = "obj_seleccionarPJ_borrar";
	global.__objectNames[272] = "obj_control_seleccionarPJ";
	global.__objectNames[273] = "obj_opciones_dif_media";
	global.__objectNames[274] = "obj_opciones_dif_alta";
	global.__objectNames[275] = "obj_opciones_sim_horarios";
	global.__objectNames[276] = "obj_opciones_no_sim_horarios";
	global.__objectNames[277] = "obj_opciones_volver";
	global.__objectNames[278] = "obj_control_opciones";
	global.__objectNames[279] = "obj_control_creditos";
	global.__objectNames[280] = "obj_manual";
	global.__objectNames[281] = "obj_flecha_der_manual";
	global.__objectNames[282] = "obj_flecha_izq_manual";
	global.__objectNames[283] = "obj_indice_manual";
	global.__objectNames[284] = "obj_indice_manual_1";
	global.__objectNames[285] = "obj_indice_manual_2";
	global.__objectNames[286] = "obj_indice_manual_3";
	global.__objectNames[287] = "obj_indice_manual_4";
	global.__objectNames[288] = "obj_indice_manual_5";
	global.__objectNames[289] = "obj_indice_manual_6";
	global.__objectNames[290] = "obj_indice_manual_7";
	global.__objectNames[291] = "obj_indice_manual_8";
	global.__objectNames[292] = "obj_indice_manual_9";
	global.__objectNames[293] = "obj_indice_manual_10";
	global.__objectNames[294] = "obj_indice_manual_11";
	global.__objectNames[295] = "obj_indice_manual_12";
	global.__objectNames[296] = "obj_gui";
	global.__objectNames[297] = "obj_flecha_abajo";
	global.__objectNames[298] = "obj_flecha_arriba";
	global.__objectNames[299] = "obj_flecha_izq";
	global.__objectNames[300] = "obj_flecha_der";
	global.__objectNames[301] = "obj_tecla_ctrl";
	global.__objectNames[302] = "obj_tecla_A";
	global.__objectNames[303] = "obj_tecla_U";
	global.__objectNames[304] = "obj_tecla_lanzar";
	global.__objectNames[305] = "obj_tecla_hechizos";
	global.__objectNames[306] = "obj_tecla_inventario";
	global.__objectNames[307] = "obj_tecla_T";
	global.__objectNames[308] = "obj_tecla_f6";
	global.__objectNames[309] = "obj_msg";
	global.__objectNames[310] = "obj_skills_libres";
	global.__objectNames[311] = "obj_seguro";
	global.__objectNames[312] = "obj_ayuda";
	global.__objectNames[313] = "obj_configuracion";
	global.__objectNames[314] = "obj_panel_opciones";
	global.__objectNames[315] = "obj_panel_items";
	global.__objectNames[316] = "obj_panel_trabajos";
	global.__objectNames[317] = "obj_area_flechas";
	global.__objectNames[318] = "obj_boton_pausa";
	global.__objectNames[319] = "obj_borde_mapa";
	global.__objectNames[320] = "obj_opcion_sonido";
	global.__objectNames[321] = "obj_numpad";
	global.__objectNames[322] = "obj_msj_basic";
	global.__objectNames[323] = "obj_INFO";
	global.__objectNames[324] = "obj_efecto_dano";
	global.__objectNames[325] = "obj_efecto_subir_skill";
	global.__objectNames[326] = "obj_efecto_falta_skill";
	global.__objectNames[327] = "obj_efecto_subir_lvl";
	global.__objectNames[328] = "obj_efecto_login";
	global.__objectNames[329] = "obj_vibracion";
	global.__objectNames[330] = "obj_particula";
	global.__objectNames[331] = "obj_nubes";
	global.__objectNames[332] = "obj_pez";
	global.__objectNames[333] = "obj_inventario";
	global.__objectNames[334] = "obj_hechizos";
	global.__objectNames[335] = "obj_cambiar_vista_hechizos";
	global.__objectNames[336] = "obj_item_basic";
	global.__objectNames[337] = "obj_oro";
	global.__objectNames[338] = "obj_item";
	global.__objectNames[339] = "obj_meditacion";
	global.__objectNames[340] = "obj_curar_veneno";
	global.__objectNames[341] = "obj_curar_heridas_leves";
	global.__objectNames[342] = "obj_curar_heridas_graves";
	global.__objectNames[343] = "obj_dardo_magico";
	global.__objectNames[344] = "obj_flecha_magica";
	global.__objectNames[345] = "obj_flecha_electrica";
	global.__objectNames[346] = "obj_misil_magico";
	global.__objectNames[347] = "obj_tormenta_de_fuego";
	global.__objectNames[348] = "obj_descarga_electrica";
	global.__objectNames[349] = "obj_apocalipsis";
	global.__objectNames[350] = "obj_paralizar";
	global.__objectNames[351] = "obj_inmovilizar";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
